<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated @ 20.08.2012 13:53:06 by service_generator (v6.1.1 from 2012-01-18 10:49:29) -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/1"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OnlineRegistrationService"
   targetNamespace="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/1">
   <wsdl:import location="import/OnlineRegistrationService_specification_1.wsdl" namespace="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/1" />
   <wsdl:binding name="OnlineRegistrationServiceSOAP" type="tns:OnlineRegistrationService">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
      <wsdl:operation name="executeOnlineRegistrationService">
         <soap:operation soapAction="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/executeOnlineRegistrationService" />
         <wsdl:input>
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" />
         </wsdl:output>
         <wsdl:fault name="OnlineRegistrationServiceFault">
            <soap:fault use="literal" name="OnlineRegistrationServiceFault" />
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="OnlineRegistrationService">
      <wsdl:port binding="tns:OnlineRegistrationServiceSOAP" name="OnlineRegistrationService">
         <soap:address location="http://localhost:9080/eb_onlineregistrationservice_router_ws/OnlineRegistrationServicePort" />
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>