<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated @ 20.08.2012 13:53:06 by service_generator (v6.1.1 from 2012-01-18 10:49:29) -->
<wsdl:definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.css.ch/eb_onlineregistrationprocess/OnlineRegistrationProcess/1"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OnlineRegistrationProcess"
    targetNamespace="http://www.css.ch/eb_onlineregistrationprocess/OnlineRegistrationProcess/1">
  <wsdl:import location="import/OnlineRegistrationProcess_specification_1.wsdl" namespace="http://www.css.ch/eb_onlineregistrationprocess/OnlineRegistrationProcess/1"/>
  <wsdl:binding name="OnlineRegistrationProcessSOAP" type="tns:OnlineRegistrationProcess">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="executeOnlineRegistrationProcess">
      <soap:operation soapAction="http://www.css.ch/eb_onlineregistrationprocess/OnlineRegistrationProcess/executeOnlineRegistrationProcess"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="OnlineRegistrationProcessFault">
        <soap:fault use="literal" name="OnlineRegistrationProcessFault"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="executeRoleSynchronizationProcess">
      <soap:operation soapAction="http://www.css.ch/eb_onlineregistrationprocess/OnlineRegistrationProcess/executeRoleSynchronizationProcess"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="OnlineRegistrationProcessFault">
        <soap:fault use="literal" name="OnlineRegistrationProcessFault"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OnlineRegistrationProcess">
    <wsdl:port binding="tns:OnlineRegistrationProcessSOAP" name="OnlineRegistrationProcess">
      <soap:address location="http://localhost:9080/eb_onlineregistrationprocess_router_ws/OnlineRegistrationProcessPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>