<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated @ 18.09.2012 13:33:43 by service_generator (v6.1.1 from 2012-01-18 10:49:29) -->
<wsdl:definitions xmlns:tns="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/1"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OnlineRegistrationService"
   targetNamespace="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/1">
   <wsdl:types>
      <xsd:schema targetNamespace="http://www.css.ch/eb_onlineregistrationservice/OnlineRegistrationService/1"
         version="1.0">
         <xsd:include schemaLocation="../xsd/OnlineRegistrationService_1.xsd" />
      </xsd:schema>
   </wsdl:types>
   <wsdl:portType name="OnlineRegistrationService">
      <wsdl:operation name="executeOnlineRegistrationService">
         <wsdl:input message="tns:ExecuteOnlineRegistrationServiceRequest" />
         <wsdl:output message="tns:ExecuteOnlineRegistrationServiceResponse" />
         <wsdl:fault name="OnlineRegistrationServiceFault" message="tns:OnlineRegistrationServiceFault"></wsdl:fault>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:message name="ExecuteOnlineRegistrationServiceRequest">
      <wsdl:part element="tns:executeOnlineRegistrationService" name="parameters" />
   </wsdl:message>
   <wsdl:message name="ExecuteOnlineRegistrationServiceResponse">
      <wsdl:part element="tns:executeOnlineRegistrationServiceResponse" name="parameters" />
   </wsdl:message>
   <wsdl:message name="OnlineRegistrationServiceFault">
      <wsdl:part element="tns:OnlineRegistrationServiceFault" name="fault" />
   </wsdl:message>
</wsdl:definitions>